<?php
// This category is automatically generated by the system and is for testing purposes only
class ModelAction extends CommonAction {

    /**
     * List
     */
    public function index(){
        /*Instantiate model*/

        $Classify = new ClassifyModel();//Column
        $Opus = new OpusModel();        //works
        $Sort = M('sort');              //classification
        $start_list = $Sort->where(array('kind'=>'sort'))->select();
        foreach ($start_list as $key=>$value){
            cookie('sort_'.$value['id'],$value['id']);
        }

        /*Get pass value*/
             $cid = I('cid');
        if($cid!=''){
            cookie('cid',$cid);
            cookie(null,'tip_');
        }

        $cid = $_COOKIE['cid'];
        $is_half = M('classify')->where(array('cid'=>$cid))->getField('type');

        $this->assign(array('is_half'=>$is_half));
        /*分类查询传值*/

        $tip_sort = I('sort');   //Top category
        //$tip_other = I('other');//Middle class

        $tip_order = I('order');//Sorting
        $tip_index = I('index');//Sort display

        $tip_use = I('use');          //use
        $tip_industry = I('industry');//industry
        $tip_style = I('style');      //style
        $tip_color = I('color');      //colour
        $tip_software = I('software');//software
         $tip_scale = I('scale');      //proportion
        $tip_type = I('type');        //Types of
        /*Get the end of the pass*/

        /*Write array*/
        //Head classification
        $tip_head = array(
            'tip_use'=>$tip_use,
            'tip_industry'=>$tip_industry,
            'tip_style'=>$tip_style,

        );
        //Middle class
        $tip_middle = array(
            'tip_color'=>$tip_color,
            'tip_software'=>$tip_software,
            'tip_scale'=>$tip_scale,
            'tip_type'=>$tip_type
        );
      
       // var_dump($tip_head);

        /*Write cookie*/
        //Head classification
        foreach ($tip_head as $key=>$value){
             if($value!=''){
                 cookie($key,$value);

             }
        }
        //Middle class
        foreach ($tip_middle as $key=>$value){
            if($value!=''){
                cookie($key,$value);
            }
        }
        //Reset subcategory options
        if($tip_sort!=''){
            $kind_son= $Sort->where(array('pid'=>$tip_sort))->getField('kind');
            cookie('tip_'.$kind_son,null);
            cookie('sort_'.$tip_sort,$tip_sort);
           }
        if(I('tip_clear')!=''){
              $clear_kind = $Sort->where(array('id'=>I('tip_clear')))->getField('kind');
              cookie('tip_'.$clear_kind,null);
        }
        //Head classification display
        $tip_head_show = array(
            'tip_use'=>cookie('tip_use'),
            'tip_industry'=>cookie('tip_industry'),
            'tip_style'=>cookie('tip_style'),

        );
        foreach ($tip_head_show as $key=>$value){
            $pid = $Sort->where(array('id'=>$value))->getField('pid');
            cookie('sort_'.$pid,null);
        }

        foreach ($_COOKIE as $key=>$value){
            $return = preg_match("/^sort_/",$key);
            if ($return==1){
                $sort_show[] = $value;
            }
        }
        $this->assign(array('sort_show'=>$sort_show));
        //Middle class
        $tip_middle_show = array(
            'tip_color'=>cookie('tip_color'),
            'tip_software'=>cookie('tip_software'),
            'tip_scale'=>cookie('tip_scale'),
            'tip_type'=>cookie('tip_type')
        );
       // var_dump($tip_head_show);
        $this->assign(array('tip_head_show'=>$tip_head_show));

        $tip_show_first = array_merge($tip_head_show,$tip_middle_show);
         $tip_show =array();
        foreach ($tip_show_first as $key=>$value){
            if ($value!=''){
                $tip_show[$key] = $value;
            }
        }
        foreach ($tip_show as $key=>$value){
            $tip_show_name = $Sort->where(array('id'=>$value))->getField('name');
            $tip_show[$key] = array('id'=>$value,'name'=>$tip_show_name);
        }
        $this->assign(array('tip_show'=>$tip_show));
        //var_dump($tip_show);

       // var_dump($tip_head_show);
        /*Write cookie end*/


        /*Integrated Query*/


        /*Navigation sign area*/
        $tip_info = $Classify->findOne(array('cid'=>$_COOKIE['cid']));
        
        $this->assign(array('tip_info'=>$tip_info));

        /*End of navigation marking area*/
 
       /*Query condition construction*/
        $where = null;
        $where = array();
        foreach ($tip_show as $key=>$value){
            $where[$key] = $value['id'];
        }
        /*End of query condition construction*/

        /*Sort build*/

        if ($tip_order!=''){
            cookie('tip_order',$tip_order);
        }
        if ($tip_index!=''){
            cookie('tip_index',$tip_index);
        }else{
            cookie('tip_index','0');
        }
        $this->assign(array('tip_index'=>cookie('tip_index')));

        $order = cookie('tip_order');

        /*End of sorting construction*/

        /*Classification query area*/
        /*Top query list*/
        if($tip_sort!=''){
            $tip_info = $Sort->where(array('pid'=>$tip_sort))->find();
            $tip_kind = $tip_info['kind'];
            cookie($tip_kind,null);
        }
        $where_sort['kind'] = array('like','sort_%');
        $sort = $Sort->where($where_sort)->select();
        foreach ($sort as $key=>$value){
            $sort_son = $Sort->where(array('pid'=>$value['id']))->select();
            $value['son'] = $sort_son;
            $sort[$key] = $value;
        }
        $this->assign(array('sort'=>$sort));

        /*Central inquiry*/
        $where_other['kind'] = array('like','other_%') ;
        $sort_middle = $Sort->where($where_other)->select();
        $middle = array();
        foreach ($sort_middle as $key_middle=>$value_middle){
            $son_kind = $Sort->where(array('pid'=>$value_middle['id']))->find();
            $kind = $son_kind['kind'];

            $sort_son = $Sort->where(array('pid'=>$value_middle['id']))->select();
            $value_middle['son'] = $sort_son;

            $middle[$kind] = $value_middle;
        }
        $sort_color = $middle['color'];
        $sort_software = $middle['software'];
        $sort_type = $middle['type'];
        $sort_scale = $middle['scale'];
        
        $this->assign(array('sort_color'=>$sort_color,'sort_software'=>$sort_software,'sort_type'=>$sort_type,'sort_scale'=>$sort_scale));

        /*End of classification query area*/

       /*Public citation*/
        $Public = new PublicAction();
        $Public->header();
        $Public->footer();
        /*End of common head and tail reference*/

        /*page number*/
        if ($_GET['p']=='') {
            $p = 1;
        } else {
            $p = $_GET['p'];
        }
        /*End of page number*/

       /*Work list display area*/
        $path =  $Classify->getPath($cid);
        $is_half = M('classify')->where(array('cid'=>$cid))->getField('type');
        if($is_half=='half'){
            $where['is_half']='1';
        }

        $OpusListShow = $Opus->getOpusList($path,$order,$where,$num=20,$p);

        $OpusList = $OpusListShow['list'];
        $page = $OpusListShow['page'];
        $count = $OpusListShow['count'];


        $user = M('user');
        for ($i=0; $i < count($OpusList) ; $i++) {      //  Loop output, time formatting


            $qqq =  $user->where('user_id',$list1[$i]['user_id'])->find();

            // dump($qq);

            $OpusList[$i]['user_nickname']=$qqq['user_nickname'];

            $OpusList[$i]['sjs']=$this->format_date(strtotime($OpusList[$i]['opus_updatetime']));
        }



       $this->assign(array('OpusList'=>$OpusList,'page'=>$page,'count'=>$count));
        /*End of the work list display area*/
        /*//List page banner diagram
         $ad = M('sys_ads');
        $adlist = $ad->where('ad_type=2')->find();
        $this->assign('adlist', $adlist);*/
       // dump($OpusList);






        $this->display(); // Output template*/





	 }














    /**
     * Details page
     */
	public function model(){
        //引用PublicAction
        $Public = new PublicAction();
        $Public->header();
        $Public->footer();

        $cid = I('cid');
        $Opus = new OpusModel();
        //Get details of the work
        $where=null;
        $where['opus_id'] = $cid;

        $OpusDetail = $Opus->getOpusDetail($where);
        $oext_views = $OpusDetail['oext_views']+1;
        $Opus->Update($where,array('oext_views'=>$oext_views));
        //Get recommended search, take keywords
        $OpusSearch = $OpusDetail['opus_keyword'];

        $OpusSearch = explode("-",$OpusSearch);

        $Sort = M('sort');

        $name_type = $Sort->where(array('id'=>$OpusDetail['tip_type']))->getField('name');
        $OpusDetail['tip_type'] = $name_type;

        $name_software = $Sort->where(array('id'=>$OpusDetail['tip_software']))->getField('name');
        $OpusDetail['tip_software'] = $name_software;



        $this->assign('OpusSearch',$OpusSearch);
        $this->assign('OpusDetail',$OpusDetail);

        //Get peer recommendation
        $SameList = $Opus->getSameList($cid);
        $this->assign('SameList',$SameList);



        //Get the comment section of the detail page
        $opus_comment = M('opus_comment');
        $where['opus_id']=$cid;      
 
        $list1 =  $opus_comment->where($where)->order('cmt_createtime DESC')->limit(10)->select();

        $user = M('user');

        for ($i=0; $i < count($list1) ; $i++) { 

            $qq =  $user->where('user_id',$list1[$i]['user_id'])->find();

            // dump($qq);

            $list1[$i]['user_nickname']=$qq['user_nickname'];


            $list1[$i]['sj']=$this->format_date(strtotime($list1[$i]['cmt_createtime']));

        }
      
        $coment =  count($list1) ;

        $this->assign('list1',$list1);

        $this->assign('coment',$coment);
      




        //Work user information
        $User = new UserModel();
        $user_id = $OpusDetail['user_id'];
        $where=null;
        $where['user_id'] = $user_id;
        
        $OpusCount = $Opus->getOpusCount($where);
        $UserInfo = $User->getUserInfo($user_id);
        $this->assign(array('OpusCount'=>$OpusCount,'UserInfo'=>$UserInfo));



    	$this->display();
    }




    public function format_date($time){
        $t=time()-$time;
        $f=array(
            '31536000'=>'years',
            '2592000'=>'months',
            '604800'=>'weeks',
            '86400'=>'days',
            '3600'=>'hours',
            '60'=>'minutes',
            '1'=>'seconds'
        );
        foreach ($f as $k=>$v)    {
            if (0 !=$c=floor($t/(int)$k)) {
                return $c.$v.'ago';
            }
        }
    }


    public function adver(){

    }

    /**
     * Download page
     */
    public function loading(){

        $cid = I('opus_id');

        $Opus = new OpusModel();
        //Get details of the work
        $where=null;
        $where['opus_id'] = $cid;
       
        $OpusDetail = $Opus->getOpusDetail($where);

        if($OpusDetail['is_half']=='1'){
           
            $half_price = $OpusDetail['prices'];      //Newly added free trading coins: gold coins
            $half_price = number_format($half_price);
            
        }
        $Sort = M('sort');

        $name_type = $Sort->where(array('id'=>$OpusDetail['tip_type']))->getField('name');
        $OpusDetail['tip_type'] = $name_type;

        $name_software = $Sort->where(array('id'=>$OpusDetail['tip_software']))->getField('name');
        $OpusDetail['tip_software'] = $name_software;

        $this->assign('half_price',$half_price);
        $this->assign('OpusDetail',$OpusDetail);
       
        //Get peer recommendation
        $SameList = $Opus->getSameList($cid);
        $this->assign('SameList',$SameList);


        $Ad = M('sys_ads');
        $ad_down = $Ad->where(array('ad_locationpic'=>'ad_down'))->find();
        $this->assign(array('ad_down'=>$ad_down));

   
        $this->display('Model/loading');
    }

}