<?php
// This category is automatically generated by the system and is for testing purposes only
class PublicAction extends CommonAction
{
    public function header()
    {

        $Chat = M('chat');

        $user_id = cookie('user_id');

        $where_c = array(
            'user_id'=>$user_id,
            'chat_state'=>'1',
            'chat_form'=>'0'
        );

        $count = $Chat->where($where_c)->count();

        $this->assign(array('new_chat'=>$count));
        //Instantiated column model
        $Classify = new ClassifyModel();
        //Generate head navigation
        $Cates = $Classify->CreateCate();
        /*        //Divide the displayed and hidden columns
                foreach($Cates as $key=>$value ){
                    if ($key<3){
                        //display
                        $cateshow[] = $value;
                    }else{
                        //hide
                        $catehide[] = $value;
                    }
                }*/
       //logo
        $Ad = M('sys_ads');
        $logo = $Ad->where(array('ad_locationpic'=>'station_logo'))->find();

        //赋值

        $this->assign(array('Cates' => $Cates,'logo'=>$logo));

    }

    public function footer()
    {

        $site = M('sys_config');
        $key = $site->where('id=5')->getField('value');
        
        $this->assign('key_show',$key);
    }

    public function phone(){
        $this->display();
    }
    
    public function we_chat(){
        $this->display('Public/weixin');
    }
    //The registration page is displayed
    public function RegisterShow()
    {
        $this->header();
        $this->footer();
        $this->display('Public/register');
    }
    //Login page display
    public function LoginShow()
    {
        $this->header();
        $this->footer();
        $this->display('Public/login');
    }
    //The forgot password page is displayed
    public function ForgetShow()
    {
        $this->header();$this->footer();
        
        $this->display('Public/forget_1');
    }

    /**
     * User login
     */
    public function login()
    {
                  //$this->error('',U('Public/forget_1'));
        if (isset($_POST['dosubmit'])) {
            $data = $_POST;
            $User = new UserModel();
            $result = $User->login($data);
            if ($result) {

                $this->success('login successful');
                //echo session('username');
            } else {

                $this->error('No such user or has been banned！', U('Public/LoginShow'));
            }
        }
    }

    public function getLoginInfo()
    {
        //Get user information
        $User = new UserModel();
        $user_id = cookie('user_id');

        $where['user_id'] = $user_id;
        $UserInfo = $User->getUserInfo($where);
        $user_name = $UserInfo['user_name'];
        $nickname = $UserInfo['user_nickname'];
        if ($nickname==null){
            $nickname = $user_name;
        }
        $user_pic = $UserInfo['user_pic'];

        //Get user account information
        $Acount = new UserAccountModel();
        $AcountInfo = $Acount->getAcountInfo($where);

        $gold_coin = $AcountInfo['gold_coin'];

        //Combined return value
        $islogin = cookie('is_login');
        $msg = array(
            'islogin' => $islogin,
            'nickname' => $nickname,
            'avar' => $user_pic,
            'amount' => $gold_coin
        );

        echo json_encode($msg);
        exit();
    }

    public function login_out()
    {

        cookie('is_login', null);
        cookie('user_id',null);
        session(null);

        $this->success('Exit successfully', U('Index/index'));
    }
    /*   public function login() {
           
           if (session('user_id')){
               $this->redirect('Service/index');}
   
           $reurl =urlencode($_GET['reurl']); //地址加密 
           $this->assign('reurl',$reurl);
           $this->display();
       }*/

    /**
     * recover password
     */
    public function forget()
    {
        $show = I('show');
       
        switch ($show){
            case 2:
                $email = I('email');
                $where['user_email'] = $email;

                $exptime = date('Y-m-d H:i:s',time()+3600*12);//Registration timeout for 24 hours
                $token = md5($email.$exptime);
                $data = array('user_exptime'=>$exptime,
                    'user_token'=>$token,);
                $User = new UserModel();
                $result = $User->save($where,$data);
                if ($result){
                    //Build activation link
                    $site = M('sys_config');
                    $SiteUrl = $site->where('id=3')->getField('value');

                    $where['user_email'] = $email;
                    $get = $User->findOne($where);

                    $token = $get['user_token'];

                    $url = $SiteUrl.'/index.php/Public/forget?show=3&token='.$token;

                    $send = $this->send_mail($email,$url);
                }


                $start = strpos($email,'@')+1;
                $len = strlen($email);
                $num = $len-$start;
                $url = substr($email,$start,$num);

                $this->assign(array('email'=>$email,'url'=>$url));
                $show_page = "Public/forget_2";
                break;
            case 3:

                $token = $_GET['token'];
                $time = date('Y-m-d H:i:s',time());

                $user = M('user');
                $where['user_token'] = $token;
                $result = $user->where($where)->find();

                $user_name = $result['user_name'];
                
                $this->assign(array('user_name'=>$user_name));
                if ($result['user_exptime']>$time){
                    $show_page = "Public/forget_3";
                }else{
                    //Delete data over time
                     $this->error('The message has expired',U('Public/ForgetShow'));
                }

                break;
            case 4:
                $user_name = I('user_name');
                $pass = I('pass');
                $cw['user_name'] = $user_name;
                $cd['user_password'] = md5($pass);

                $User = new UserModel();
                $result = $User->save($cw,$cd);
                if ($result){
                    $show_page = "Public/forget_4";
                }else{
                    $this->error('Unknown error, please try again or contact the administrator',U('Public/ForgetShow'));
                }

                break;
        }
        if ($show==""){
            $show_page = "Public/forget_1";
        }

        //$this->show('Not open yet');
        $this->header();$this->footer();
        $this->display($show_page);
    }

    /**
     * User logout
     */
    public function logout()
    {
        session_destroy();
        cookie('user_nickname', null);
        cookie('user_pic', null);

        $this->redirect("/index");
    }


    //Verification code
    Public function verify()
    {
        import('ORG.Util.Image');//Local use

        Image::buildImageVerify(4, 3, 'png', 80, 38, 'verity');//usage($length,$mode,$type,$width,$height,$verifyName)
        // Image::GBVerify(4, 'png', 1, 38, 'SIMHEI.TTF', 'verify');//Font files can be found under the Fonts directory of the window
    }
public function show(){
    var_dump($_SESSION['verify']);
    var_dump($_COOKIE['de']);

}
    Public function checkverify()
    {
      session('de', md5(I('param'))) ;
     
        //Every time a verification code is generated, the string information after md5 of the verification code will be recorded through SESSION
        //The verify name depends on the value of the verifyName parameter of your verification code.
        if ($_SESSION['verify'] != md5($_GET['param'])) {
            echo '{ "info":"验证码错误","status":"n"}';
            // $this->error('Verification code error！');
        } else {
            echo '{
                "info":"",
                "status":"y"
            }';
        }
    }



 
    //Email registration operation
    public function register()
    {

        if (isset($_POST)){
            //retrieve data
            $user_name = $_POST['username'];    //account number
            $user_password = md5($_POST['password']);//password
            $user_email = $_POST['email'];      //mailbox
            $emailword = $_POST['emailword'];      //E-mail verification code
            $ip = get_client_ip();              //User ip
            $time = date('Y-m-d H:i:s',time()); //Creation time
            $exptime = date('Y-m-d H:i:s',time()+3600*24);//Registration timeout for 24 hours
            $token = md5($user_name.$user_password.$time);

			
			 $emil = M("emil"); //Verify whether other users have registered their email addresses, add and send the activation code if they haven’t
		
		$where['user_email'] = $user_email;	
			
	     $jianyan = $emil->where($where)->find(); //  Determine whether there is a registered email address
              $int= $jianyan['int'];
		 
			 if ($emailword == $int) {		
			
			             //Build new data
            $data = array(
                'user_name'=>$user_name,
                'user_password'=>$user_password,
                'user_email'=>$user_email,
                'user_registertime'=>$time,
                'user_registerip'=>$ip,
                'user_exptime'=>$exptime,
                'user_token'=>$token,
				'user_emailState'=>'1', 
				'user_state'=>'1',
                'user_pic'=>'/Public/images/header-img.jpg'
            );


            //Create data
            $User = new UserModel();
           $User->addData($data);
          //  if ($result){

                //Build activation link
      //          $site = M('sys_config');
     //           $SiteUrl = $site->where('id=3')->getField('value');

     //           $where['user_name'] = $user_name;
    //            $get = $User->findOne($where);
//
      //          $token = $get['user_token'];

       //         $url = $SiteUrl.'/index.php/Public/activate?token='.$token;

        //        $send = $this->send_mail($user_email,$url);
          //  if ($send){
                $this->success('registration success! Welcome to LOGO.com, activation and registration have been completed!',U('Index/index'));
            }else{
            //    $where['user_name'] = $user_name;

           //     $User->delData($where);

                $this->error('verification failed! Please check your email address or resend the verification code!');
            }
            }
			
			
			
			
			 }
			



    //    }
   // }
	
	
	
	
    //Email registration activation
    public function activate(){
        if (isset($_GET)){
            $token = $_GET['token'];
            $time = date('Y-m-d H:i:s',time());

            $user = M('user');
            $where['user_token'] = $token;
            $result = $user->where($where)->find();
            $user_id = $result['user_id'];
            //Whether the activation timed out
            if ($result['user_exptime']>$time){
                //Modify account status
                $data = array('user_emailState'=>'1', 'user_state'=>'1');
                $user->where($where)->save($data);
                //Create account data
                $Account = new UserAccountModel();
                $data = array('user_id'=>$user_id,'time'=>date( 'Y-m-d H:i:s'));
                $Account->addData($data);

                $this->success('Activated successfully！',U('Index/index'));
            }else{
                //Delete data over time
                $user->where($where)->delete();
                
                $this->error('The registration email has timed out, please re-register!',U('Public/RegisterShow'));
            }
        }
    }

    /**
     * Login verification
     */
    public function check_login(){
        if (isset($_GET)) {
            //Get pass value
            $clientid = $_GET['clientid'];
            $user_name = $_GET[$clientid];

            //Inquire
            $where['user_name|user_email'] = $user_name;
            $User = new UserModel();
            $result = $User->findOne($where);
cookie('de',$result);
            //Verification returns
            if ($result) {
                echo '{
                "status":"true"
                }';
                exit();
            } else {
                echo '{
                "status":"false";
              
            }';

            }
            exit();
        }
        else{
            $this->error('Data verification failure, please try again!', U('Public/register'));
        }
    }
    //User name uniqueness verification
    Public function check_name()
    {
        if (isset($_GET)) {
            //Get pass value
            $clientid = $_GET['clientid'];
            $user_name = $_GET[$clientid];
            //Inquire
            $where['user_name|user_email'] = $user_name;
            
            $User = new UserModel();
            $result = $User->findOne($where);

            //Verification returns
            if (empty($result)) {
                echo '{
                "status":"true"
                }';
                exit();
            } else {
                echo '{
                "status":"false";
                   }';

            }
            exit();
        }
        else{
                $this->error('Data verification failure, please try again!', U('Public/register'));
            }

      
    }
    //Password validation
    public function check_pass()
    {
        if (isset($_GET)) {
            $clientid = $_GET['clientid'];
            $user_pass = $_GET[$clientid];

            $pre = "[\\!|@|#|\\$|%|\\^|&|\\*|\\(|\\)|_|\\+|\\||-|=|\\\\|~|`|:|\\\"|\\<|\\>|\\?|;|'|,|\\.|/|“|”|；|：|，|。|、|·|\\{|\\}|\\[|\\]]";

            if (preg_match($pre, $user_pass)) {
                echo '{
                "status":""
                }';

            } else {
                echo '{
                "status":"true"
                }';
            }
            exit();

        }else {
            $this->error('Data verification failure, please try again！', U('Public/register'));
        }
    }
    //Email uniqueness verification
    Public function check_email(){
        if (isset($_GET)){
            //Get pass value
            $clientid = $_GET['clientid'];
            $email = $_GET[$clientid];

            $where['user_email'] = $email;
            $User = new UserModel();
            $result = $User->findOne($where);

            if (empty($result)) {
                echo '{
                "status":"true"
                }';
              
            } else {
                echo '{
                "status":"";
                         }';
                
            }exit();
        }else{
            $this->error('Data verification failure, please try again!',U('Public/register'));
        }

    }





}