<?php
// This category is automatically generated by the system and is for testing purposes only
class AccountAction extends CommonAction {

    /**
     * Recharge record
     *
     * */
    public function recharge(){
        if($_POST['select']){
            $Reg = M('user_recharge');
            $select = $_POST['select'];

            $where['id'] = array('in',$select);

            $result =  $Reg->where($where)->delete();

            if ($result){
                $this->redirect('Account/recharge');
            }else{
                $this->redirect('Account/recharge','','2','failed to delete');
            }
        }else{


        $UserRecharge = new UserRechargeModel();
        $User = M('user');
        if($_GET['p']){
            $p = $_GET['p'];
        }else{
            cookie('admin_search',$_POST['searchop']);
            $p='1';
        }
        $where=array();
            $this->assign(array('search'=>cookie('admin_search')));
       if($_POST['searchop']){
                cookie('admin_search',$_POST['searchop']);
       }
            $search = cookie('admin_search');

            if($search!=null) {
                $where_u['user_name'] = array('like', '%' . $search . '%');
                $where_u['user_nickname'] = array('like', '%' . $search . '%');
                $where_u['_logic'] = 'or';

                $result = $User->where($where_u)->select();
                $id_list = array();
                if($result){
                    foreach ($result as $key=>$value){
                        $id_list = $value['user_id'];
                    }
                    $where['user_id'] = array('in',$id_list);
                }

                $where['acct_order'] = array('like', '%' . $search . '%');
                $where['_logic'] = 'or';

            }

              $RechargeListShow = $UserRecharge->getRechargeList($where,$num=50,$p);

        foreach($RechargeListShow['list'] as $key=>$value){
            $user_info = $User->where(array('user_id'=>$value['user_id']))->find();
            $value['user_name']= $user_info['user_name'];
            $user_nickname = $user_info['user_nickname'];
            if($user_nickname==null){
                $user_nickname = 'Not yet';
            }
            $value['user_nickname'] = $user_nickname;
            $RechargeListShow['list'][$key] = $value;
        }
        $this->assign($RechargeListShow);
        }
        $this->display(); // Output template
	}

    /**
     * Purchase History
     */
	public function pay(){
        if($_POST['select']){
            //delete
            $where['id'] = array('in',$_POST['select']);

            $Down = M('opus_download');

            $result = $Down->where($where)->delete();

            if($result){
                $this->redirect('Account/pay');
            }else{
                $this->redirect('Account/pay','','2','Failed to delete');
            }
        }
        else{
            //Query, display
            $Down = new OpusDownloadModel();
            $User = M('user');

            if($_GET['p']){
                $p = $_GET['p'];
            }else{
                cookie('admin_search',null);
                $p = '1';
            }
            $where = array();

            if($_POST['searchop']){
                cookie('admin_search',$_POST['searchop']);

            }
            $search = cookie('admin_search');
            $this->assign(array('search'=>cookie('admin_search')));

            //Build query conditions
            if($search!=null){
                $where_u['user_nickname']=array('like','%'.$search.'%');
                $where_u['user_name'] = array('like','%'.$search.'%');
                $where_u['_logic'] = 'or';
                $result = $User->where($where_u)->select();
                $id_list = array();
                if($result){
                    foreach ($result as $key=>$value){
                        $id_list = $value['user_id'];
                    }
                    $where['user_id'] = array('in',$id_list);
                }
                $where['opus_title'] = array('like','%'.$search.'%');
                $where['order_number'] = array('like','%'.$search.'%');
                $where['_logic'] = 'or';
            }

            $DownList = $Down->getDownList($where,$num=50,$p);
            //Add information processing
            foreach ($DownList['list'] as $key=>$value){
                $user_info = $User->where(array('user_id'=>$value['user_id']))->find();
                $user_name = $user_info['user_name'];
                $user_nickname = $user_info['user_nickname'];
                if($user_nickname==null){
                    $user_nickname = 'Not yet';
                }
                $value['user_name'] = $user_name;
                $value['user_nickname'] = $user_nickname;
                $DownList['list'][$key] = $value;
            }


            $this->assign($DownList);

        }



        $this->display(); // Output template
	}
    /**
     * Income record
     **/
	public function income(){
        if($_POST['select']){
            //delete
            $where['id'] = array('in',$_POST['select']);

            $Down = M('opus_download');

            $result = $Down->where($where)->delete();

            if($result){
                $this->redirect('Account/pay');
            }else{
                $this->redirect('Account/pay','','2','Failed to delete');
            }
        }
        else{
            //Query display
            $Down = new OpusDownloadModel();
            $User = M('user');

            if($_GET['p']){
                $p = $_GET['p'];
            }else{
                cookie('admin_search',null);
                $p = '1';
            }
            $where = array();

            if($_POST['searchop']){
                cookie('admin_search',$_POST['searchop']);

            }
            $search = cookie('admin_search');
            $this->assign(array('search'=>cookie('admin_search')));

            //构建查询条件
            if($search!=null){
                $where_u['user_nickname']=array('like','%'.$search.'%');
                $where_u['user_name'] = array('like','%'.$search.'%');
                $where_u['_logic'] = 'or';
                $result = $User->where($where_u)->select();
                $id_list = array();
                if($result){
                    foreach ($result as $key=>$value){
                        $id_list = $value['user_id'];
                    }
                    $where['seller_id'] = array('in',$id_list);
                }
                $where['opus_title'] = array('like','%'.$search.'%');
                $where['order_number'] = array('like','%'.$search.'%');
                $where['_logic'] = 'or';
            }

            $DownList = $Down->getDownList($where,$num=50,$p);
            //Add information processing
            foreach ($DownList['list'] as $key=>$value){
                $user_info = $User->where(array('user_id'=>$value['seller_id']))->find();
                $user_name = $user_info['user_name'];
                $user_nickname = $user_info['user_nickname'];
                if($user_nickname==null){
                    $user_nickname = 'Not yet';
                }
                $value['user_name'] = $user_name;
                $value['user_nickname'] = $user_nickname;
                $DownList['list'][$key] = $value;
            }


            $this->assign($DownList);

        }

        $this->display(); // Output template
	}
    /**
     * Withdrawals record
     */
	public function withdraw(){
        if($_POST['select']){
            //delete
            $where['id'] = array('in',$_POST['select']);

            $Con = M('user_consume');

            $result = $Con->where($where)->delete();

            if($result){
                $this->redirect('Account/withdraw');
            }else{
                $this->redirect('Account/withdraw','','2','Failed to delete');
            }
        }
        else{
            //Query display
            $Down = new UserConsumeModel();
            $User = M('user');
            $Acc = M('user_account');

            if($_GET['p']){
                $p = $_GET['p'];
            }else{
                cookie('admin_search',null);
                $p = '1';
            }
            $where_new = array('method'=>'3');

            if($_POST['searchop']){
                cookie('admin_search',$_POST['searchop']);

            }
            $search = cookie('admin_search');
            $this->assign(array('search'=>cookie('admin_search')));

            //构建查询条件
            if($search!=null){
                $where_u['user_nickname']=array('like','%'.$search.'%');
                $where_u['user_name'] = array('like','%'.$search.'%');
                $where_u['_logic'] = 'or';
                $result = $User->where($where_u)->select();
                $id_list = array();
                if($result){
                    foreach ($result as $key=>$value){
                        $id_list = $value['user_id'];
                    }
                    $where['seller_id'] = array('in',$id_list);
                }
                $where['model_type'] = array('like','%'.$search.'%');
                $where['order'] = array('like','%'.$search.'%');
                $where['_logic'] = 'or';

                $where_new['_complex'] = $where;

            }

            $DownList = $Down->getConsumeList($where_new,$num=50,$p);
            //Add information processing
            foreach ($DownList['list'] as $key=>$value){
                $user_info = $User->where(array('user_id'=>$value['user_id']))->find();
                $user_name = $user_info['user_name'];
                $user_nickname = $user_info['user_nickname'];
                if($user_nickname==null){
                    $user_nickname = 'Not yet';
                }
                $coin = $Acc->where(array('user_id'=>$value['user_id']))->getField('gold_coin');
                $value['gold_coin'] = $coin;
                $value['user_name'] = $user_name;
                $value['user_nickname'] = $user_nickname;
                $DownList['list'][$key] = $value;
            }


            $this->assign($DownList);

        }
        $this->display(); // Output template
	}
	public function count(){
	    $Acc  = M('user_account');
	    $Rec  = M('user_recharge');
	    $Con  = M('user_consume');
        if(I('data')){
            $getdata=I('data');
        }
        if(I('day')){
            $getdata = I('day');
        }

        // strtotime("2015-05-22 15:00:00");
        $this->assign('currentday',$getdata);

        if($getdata==null){
            $d='';
            $a=date ( 'Y-m-d H:i:s');

        }else{
            $a=date ( 'Y-m-d H:i:s');
            if($getdata=='1'){
                $d=date ( 'Y-m-d');
            }else{
                $d=date ( 'Y-m-d H:i:s',time()-3600*24*$getdata);
            }

        }
        $where = array($d,$a);
        //Site balance
        $gold_coin = $Acc->sum('gold_coin');
        //Recharge
        $rec_coin = $Rec->where(array('acct_time'=>array('between',$where),'acct_status'=>'3'))->sum('acct_money');
        //expenditure
        $Con_out = $Con->where(array('time'=>array('between',$where),'method_status'=>'0','over'=>'1'))->sum('money');
        //income
         $Con_in = $Con->where(array('time'=>array('between',$where),'method_status'=>'1','over'=>'1'))->sum('money');

        //withdraw
         $Con_xian = $Con->where(array('time'=>array('between',$where),'method'=>'3','over'=>'1'))->sum('money');
        //Total gold
        $total = $gold_coin+$Con_xian;
        $data = array(
            'gold_coin'=>$gold_coin,
            'rec_coin'=>$rec_coin,
            'con_out'=>$Con_out,
            'con_in'=>$Con_in,
            'con_xian'=>$Con_xian,
            'total'=>$total
        );

        $this->assign($data);
	  $this->display();
    }

    public function recover(){
        $id=$this->_request('id');
        // var_dump($id);die();
        $user=M('sys_tran');
        $data['tran_id']=$id;
        $user->where($data)->setField('tag','1');
        if($id)
        {
            $this->success('Total gold!');
        }
        else
        {
            $this->error('Recovery failed!');
        }
    }

    public function rec(){
        $mt = $_POST['mt'];
        $dat = $_POST['check'];
        $map['tran_id']  = array('in',$dat);
        $data['tag'] = '1';
// var_dump($mt);die();
        if (empty($dat)) {
            $this->error('Please tick！');
        } else {
            if ($mt == 1) {
                $p = M('sys_tran')->where($map)->save($data);
                if ($p) {
                    $this->success('All restored successfully！');
                } else {
                    $this->error('All recovery failed！');
                }
            } else {
                $d = M('sys_tran')->where($map)->delete();
                $this->success('Deleted selected！');
            }
        }
    }

	public function updateCash(){
        $ret = array(
            'status' => 1,
            'msg' => 'please sign in'
        );
        if(session('admin_name') && session('admin_id')){
            $cash = M('cash');
            $condition['id'] = $_POST['id'];
            $data['cash_status'] = $_POST['money'];
            $ret2 = $cash->where($condition)->save($data);
            if($ret2){
                $ret['status'] = 0;
                $ret['msg'] = 'Update completed';
            }else{
                $ret['msg'] = 'Update failed';
            }
        }

        $this->ajaxReturn($ret);
    }

	public function verify(){
		$id=$this->_request('id');
        if($id)
        {
            $cash=M('cash');
            $data['id']=$id;
            $rs=$cash->where($data)->find();
			if($rs['status']==1){
				$cash-> where($data)->setField('status','0');
				$this->redirect("account/withdraw");
				//$this->success('Withdrawn!');
			}else{
				//$cash-> where($data)->setField('status','1');
				$this->redirect("account/withdraw");
				//$this->success('Not withdrawn!');
			}
        }
        else{
            $this->error('Unsuccessful review!');
        }
	}


    public function bank(){

         if($_POST['select']){

             $Reg = M('user_recharge');
             $Acc = M('user_account');
             $Con = M('user_consume');
             $Chat = M('chat');
             $select = $_POST['select'];

             foreach ($select as $key=>$value){


                 $data_new = array('acct_status'=>'3');
                 $where_new = array('id'=>$value);
                  //Update status, query information
                $Reg->where($where_new)->save($data_new);
                 $info_new = $Reg->where($where_new)->find();



                 //Account value increase
                 $acc_gold = $Acc->where(array('user_id'=>$info_new['user_id']))->getField('gold_coin');

                 $gold = $acc_gold+intval($info_new['acct_money'],10);
                 $Acc->where(array('user_id'=>$info_new['user_id']))->save(array('gold_coin'=>$gold));

                 //Transaction Record
                 $data_con = array(
                     'user_id'=>$info_new['user_id'],
                     'order'=>$info_new['acct_order'],
                     'time'=>$info_new['acct_time'],
                     'model_type'=>'Bank Transfer',
                     'money'=>$info_new['acct_money'],
                     'method_status'=>'1',
                     'method'=>'1',
                     'ip'=>$info_new['ip'],
                     'over'=>'1'
                 );

              $Con->data($data_con)->add();

                 $data_chat = array(
                     'user_id'=>$info_new['user_id'],
                     'chat_state'=>'1',
                     'chat_content'=>'Your order with an amount of：'.$info_new['acct_money'].'has been processed',
                     'chat_title'=>'User recharge',
                     'chat_form'=>'0',
                     'chat_time'=>date("Y-m-d H:i:s")
                 );

               $Chat->data($data_chat)->add();

             }
             $this->redirect('Account/bank');

            }else{

             $UserRecharge = new UserRechargeModel();
             $User = M('user');
             $User_account = M('user_account');
             if($_GET['p']){
                 $p = $_GET['p'];
             }else{
                 cookie('admin_search',$_POST['searchop']);
                 $p='1';
             }
             $where=array();
             $this->assign(array('search'=>cookie('admin_search')));
             if($_POST['searchop']){
                 cookie('admin_search',$_POST['searchop']);
             }
             $search = cookie('admin_search');

             if($search!=null) {
                 $where_u['user_name'] = array('like', '%' . $search . '%');
                 $where_u['user_nickname'] = array('like', '%' . $search . '%');
                 $where_u['_logic'] = 'or';

                 $result = $User->where($where_u)->select();
                 $id_list = array();
                 if($result){
                     foreach ($result as $key=>$value){
                         $id_list = $value['user_id'];
                     }
                     $where['user_id'] = array('in',$id_list);
                 }

                 $where['acct_order'] = array('like', '%' . $search . '%');
                 $where['_logic'] = 'or';

             }
             $where['acct_method'] = '3';
             $where['acct_status'] = '2';

             $RechargeListShow = $UserRecharge->getRechargeList($where,$num=50,$p);

             foreach($RechargeListShow['list'] as $key=>$value){
                 $user_info = $User->where(array('user_id'=>$value['user_id']))->find();
                 $value['user_name']= $user_info['user_name'];
                 $user_nickname = $user_info['user_nickname'];
                 $acc_info = $User_account->where(array('user_id'=>$value['user_id']))->find();

                 $user_realname = $acc_info['acct_name'];
                 $user_bank = $acc_info['acct_bank'];
                 $user_account = $acc_info['acct_account'];

                 $value['user_acct_name'] =  $user_realname;
                 $value['user_bank'] = $user_bank;
                 $value['user_account'] = $user_account;

                 if($user_nickname==null){
                     $user_nickname = 'Not yet';
                 }
                 $value['user_nickname'] = $user_nickname;
                 $RechargeListShow['list'][$key] = $value;
             }
             $this->assign($RechargeListShow);
         }
	    $this->display();

     }

}