<?php
// This category is automatically generated by the system and is for testing purposes only
class OpusAction extends CommonAction {
    /**
     * Work Management Home
     */
    public function index(){
        $Opus = new OpusModel();
        $User  = M('user');
        $Class = M('classify');

        if($_GET['p']){
            $p = $_GET['p'];
        }else{
            cookie('admin_search',null);
            $p = '1';
        }

        $where=array();
		if($_POST){
		     cookie('admin_search',$_POST['searchop']);

        }
        $search = cookie('admin_search');
        if($search!=null){
            $where_c['name']=array('like',$search);
            $result = $Class->where($where_c)->find();
            if($result) {
                $path = $result['path'].'-'.$result['cid'];
                $where['opus_sort'] = array('like',$path."%");
            }
               $where['opus_title'] = array('like','%'.$search.'%');
               $where['_logic'] = 'or';
        }

        $this->assign(array('search'=>cookie('admin_search')));

		 $ShowList = $Opus->getOpusList($order='opus_id',$where,$num='50',$p);

		 foreach($ShowList['list'] as $key=>$value){
			 			 
				 $user_name = $User->where(array('user_id'=>$value['user_id']))->getField('user_nickname');
				 
				 $value['user_nickname']= $user_name;
				 
				 preg_match("/[0-9]+-[0-9]+-([0-9]+)/",$value['opus_sort'],$match);
				 $cid= $match[1];
				 $cate = $Class->where(array('cid'=>$cid))->getField('name');
			     $value['cate'] = $cate;
				 
				 			  
				 $ShowList['list'][$key] = $value;
				 
			
		 }
	
	
		 
		 $this->assign($ShowList);

		$this->display(); // Output template
    }
    

	public function check(){
		$id=$this->_request('id');
        // var_dump($id);die();
        if($id)
        {
            $opus=M('opus');
            $data['opus_id']=$id;
            $rs=$opus->where($data)->find();
            if ($rs['opus_verify']== 1) {
                $this->error('Do not repeat review！');
            } else {
               $opus-> where($data)->setField('opus_verify','1');

               $value = $rs['user_id'];
               // var_dump($value );
                $title = 'Notification of approval of works';
                $content = 'Your work has been approved by the application, if the work is excellent and recommended, it will be displayed on the homepage!';
        
                $data = array(
                    'chat_title'=>$title,
                    'chat_content'=>$content,
                    'chat_form'=>'0',
                    'chat_state'=>'1',
                    'chat_time'=>date('Y-m-d H:i:s')
                );
                // var_dump($rs);die();
				   $Chat = M('chat');
                   $data['user_id'] = $value;
                   $Chat->data($data)->add();
                $this->success('Examination passed!');
            }
        }
        else
        {
            $this->error('Unsuccessful review!');
        }
		
    }
   
    
    
	public function checkroom(){
		$id=$this->_request('id');
        // var_dump($id);die();
        if($id)
        {
            $opus=M('opus');
            $data['opus_id']=$id;
            $rs=$opus->where($data)->find();
            if ($rs['recom']== 1) {
                $this->error('Do not repeat recommendations！');
            } else {
               $opus-> where($data)->setField('recom','1');

               $value = $rs['user_id'];
              // var_dump($value );
               $title = 'Work recommendation notice';
               $content = 'Special recommendation applications have been given due to excellent works or other special reasons, and the recommended works will be displayed on the homepage！';
       
               $data = array(
                   'chat_title'=>$title,
                   'chat_content'=>$content,
                   'chat_form'=>'0',
                   'chat_state'=>'1',
                   'chat_time'=>date('Y-m-d H:i:s')
               );
       
                   $Chat = M('chat');
                   $data['user_id'] = $value;
                   $Chat->data($data)->add();



                // var_dump($rs);die();
                $this->success('Recommended successfully!');
            }
        }
        else
        {
            $this->error('Unsuccessful recommendation!');
        }
		
    }














	public function uncheck(){
		$id=$this->_request('id');
        // var_dump($id);die();
        if($id)
        {
            $opus=M('opus');
            $data['opus_id']=$id;
            $rs=$opus->where($data)->find();
            if ($rs['opus_verify']== 2) {
                $this->error('Do not return repeatedly！');
            } else {
               $opus-> where($data)->setField('opus_verify','2');


               $value = $rs['user_id'];
              // var_dump($value );
               $title = 'Notification of Return of Works';
               $content = 'The application for review has been cancelled due to duplicate works or other reasons, please contact customer service staff if you have any questions！';
       
               $data = array(
                   'chat_title'=>$title,
                   'chat_content'=>$content,
                   'chat_form'=>'0',
                   'chat_state'=>'1',
                   'chat_time'=>date('Y-m-d H:i:s')
               );
       
                   $Chat = M('chat');
                   $data['user_id'] = $value;
                   $Chat->data($data)->add();



                // var_dump($rs);die();
                $this->success('Don\'t pass!');
            }
        }
        else
        {
            $this->error('Unsuccessful review!');
        }
		
	}

    /**
     * Works deleted
     */





	public function delete(){

	    if($_POST)
	    {
			$del = $_POST['select'];
	        $opus=M('opus');
			$data['opus_id']=array('in',$del);
            $filelist = $opus->where($data)->select();

            foreach ($filelist as $key=>$value) {
                $file_list[] = $value['opus_source'];
            }

            foreach ($file_list as $key=>$value){
                if($value!=null || $value!=''){
                    $path = $_SERVER['DOCUMENT_ROOT'].$value;
                    unlink($path);

                }
            }

			$result = $opus->where($data)->delete();
            if($result){
                $this->redirect('Opus/index');
            }else
            {
                $this->redirect('Opus/index','','2','Failed to delete！');
            }

	    }

	}

        public function count(){
			
			if(I('data')){
            $getdata=I('data');
        }
        if(I('day')){
            $getdata = I('day');
        }
        
        // strtotime("2015-05-22 15:00:00");
        $this->assign('currentday',$getdata);
		
        if($getdata==null){
			$d='';
			$a=date ( 'Y-m-d H:i:s');
			
		}else{
			
			$a=date ( 'Y-m-d H:i:s');
			if($getdata=='1'){
				$d=date ( 'Y-m-d');
			}else{
				$d=date ( 'Y-m-d H:i:s',time()-3600*24*$getdata);
			}
			
		}
		$where = array($d,$a);
		
		
		   $Opus = new OpusModel();
		   $Class = new ClassifyModel(); 
		   $Down = new OpusDownloadModel();
		   
		   // 各栏目作品数
		 
		  $CateList = $Class->CreateCate();
		  foreach($CateList as $key=>$value){
			  $path = $value['path'].'-'.$value['cid'];
			  
			  $count = $Opus->getOpusCount(array('opus_sort'=>$path,'opus_createtime'=>array('between',$where)));
			  $value['count'] = $count;
			  $CateList[$key] = $value;
			  
		  }
		  $count_down = $Down->getDownCount(array('down_time'=>array('between',$where)));
		  $tran = $Down->getDownSum(array('down_time'=>array('between',$where)),'down_price');
		  if($tran==null){
			  $tran = number_format(0,2);
		  };
		  
		  
		  
		  
		  
		  $count_all = $Opus->getOpusCount(array('opus_createtime'=>array('between',$where)));
		  
		  
		  //var_dump($CateList);
		  $this->assign(array('cate_list'=>$CateList,'total'=>$count_all,'count_down'=>$count_down,'tran'=>$tran));
		  
		
          $this->display('Opus/count');
    }

    /**
     * download
     */
	    public function down(){

	        $OpusDown = new OpusDownloadModel();
	        $User = M('user');

            if($_GET['p']){
                $p = $_GET['p'];
            }else{
                cookie('admin_search',null);
                $p = '1';
            }
            $where = array();

            if($_POST){
                cookie('admin_search',$_POST['searchop']);

            }
            $search = cookie('admin_search');

            if($search!=null){
                $where_u['user_nickname']=array('like','%'.$search.'%');
                $where_u['user_name'] = array('like','%'.$search.'%');
                $where_u['_logic'] = 'or';
                $result = $User->where($where_u)->select();
                if($result){
                    foreach ($result as $key=>$value){
                        $id_list = $value['user_id'];
                    }
                    $where['user_id'] = array('in',$id_list);
                }
                $where['opus_title'] = array('like','%'.$search.'%');
                $where['order_number'] = array('like','%'.$search.'%');
                $where['_logic'] = 'or';
            }
            $this->assign(array('search'=>cookie('admin_search')));
           $ShowList =  $OpusDown->getDownList($where,$num='50',$p);

            foreach($ShowList['list'] as $key=>$value){
                $seller_result = $User->where(array('user_id'=>$value['seller_id']))->find();
                $buyer_result = $User->where(array('user_id'=>$value['user_id']))->find();

                $seller_nickname = $seller_result['user_nickname'];
                $seller_name = $seller_result['user_name'];
                $buyer_nickname = $buyer_result['user_nickname'];
                $buyer_name = $buyer_result['user_name'];


                if($seller_nickname==null ||$seller_nickname==''){
                    $seller_nickname = 'No nickname';
                }
                if($buyer_nickname==null ||$buyer_nickname==''){
                    $buyer_nickname = 'No nickname';
                }
                $value['buyer_name'] = $buyer_name;
                $value['seller_name'] = $seller_name;

                $value['buyer_nickname'] = $buyer_nickname;
                $value['seller_nickname'] = $seller_nickname;
                $ShowList['list'][$key]=$value;
            }

          $this->assign($ShowList);

          $this->display(); // Output template

    }

    public function down_del(){
        $OpusDown = new OpusDownloadModel();
	        if($_POST){
	            $id_list = $_POST['select'];
                $where['id'] = array('in',$id_list);


               $result = $OpusDown->Delete($where);
               if($result){
                   $this->redirect('Opus/down');
               }else{
                   $this->redirect('Opus/down','','2','Failed to delete！');
               }
            }
    }
    /**
     * Upload record
     */
	public function upload(){
    	$Opus = new OpusModel();
		$User = M('user');

        if($_GET['p']){
            $p = $_GET['p'];
        }else{
            cookie('admin_search',null);
            $p = '1';
        }
        $where = array();

        if($_POST){
            cookie('admin_search',$_POST['searchop']);

        }
        $search = cookie('admin_search');

        if($search!=null){
            $where_u['user_nickname']=array('like','%'.$search.'%');
            $where_u['user_name'] = array('like','%'.$search.'%');
            $where_u['_logic'] = 'or';
            $result = $User->where($where_u)->select();

            if($result){
                foreach ($result as $key=>$value){
                    $id_list = $value['user_id'];
                }
                $where['user_id'] = array('in',$id_list);
            }
            $where['opus_title'] = array('like','%'.$search.'%');
            $where['_logic'] = 'or';

        }
        $this->assign(array('search'=>cookie('admin_search')));

		$ShowList = $Opus->getOpusList($order='opus_id',$where,$num='50',$p);

		foreach($ShowList['list'] as $key=>$value){

            $result = $User->where(array('user_id'=>$value['user_id']))->find();
           $user_nickname = $result['user_nickname'];
           $user_name = $result['user_name'];
            if($user_nickname==''||$user_nickname==null){
                $user_name = '暂无昵称';
            }
            $value['user_nickname']= $user_nickname;
            $value['user_name']= $user_name;

            $ShowList['list'][$key] = $value;
        }
		$this->assign($ShowList);

		$this->display(); // Output template
	}


}